lavalink:
  server:
    bufferDurationMs: 100
    gc-warnings: true
    password: youshallnotpass
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: false
      mixer: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: true
    youtubePlaylistLoadLimit: 1
    youtubeSearchEnabled: true
logging:
  file:
    max-history: 30
    max-size: 1GB
  level:
    lavalink: INFO
    root: INFO
  path: ./logs/
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
server:
  address: 0.0.0.0
  port: 2333
